### ISSUE TITLE
Registro: Mensaje con errores x no reconocimiento de acentos.

### ISSUE THREAD

**Issue by WEREMSOFT** [WEREMSOFT/nka20140804#1]
En el msj de bienvenida que se abre posterior a la registro de un nuevo usuario no se decodifican bien los acentos. Por alguna razon el "&aacute;" no se convierte en "á". Por ej en lugar de leerse "dirección" se lee "direcci&oacute;n".

**Comment by WEREMSOFT** [comment]
No omprendo el error, que tengo que hacer para reproducirlo? Cual es el texto que muestra?

**Comment by tvillani** [comment]
El error es muy sencillo. No reconoce los acentos de las palabras a través del encoding para HTML.
"&aacute;" no se convierte en "á", por lo que en lugar de leerse "deberás" se lee "deber&aacute;s".
Para reproducirlo, registrate como nuevo usuario y en el msj de bienvenida vas a ver el error.

**Comment by WEREMSOFT** [comment]
Resuelto.

**Comment by tvillani** [comment]
Solucionado. Disculpá que cuando lo escribía el html de esta pág me lo convertía correctamente entonces no se visualizaba bien lo q t quería decir.

**Comment by WEREMSOFT** [comment]
Perfecto, cierro el bug.

Gracias!
