### ISSUE TITLE
Error al registrar un cliente

### ISSUE THREAD

**Issue by WEREMSOFT** [WEREMSOFT/nka20140804#12]
Cuando se registra un usuario desde la aplicación, los alerts se ven mal, aparecen como "prompts", es decir, muestran un texto(que esta correcto) pero tienen un campo de texto para incluir información.

**Comment by WEREMSOFT** [comment]
Solucionado en 4.x, pendiente en 2.3

**Comment by WEREMSOFT** [comment]
Resuelto

**Comment by tvillani** [comment]
Te referís al registro inicial de un nuevo usuario?
Si es así, los promps me salen correctamente, sin campo de texto.
Si te referís a otra cosa por favor detallamelo un poco más.

**Comment by WEREMSOFT** [comment]
Asumo que esta ok.
