### ISSUE TITLE
Links mapas

### ISSUE THREAD

**Issue by WEREMSOFT** [WEREMSOFT/nka20140804#13]
En la página de contacto, al hacer clic en el mapa no linkea a google maps.

**Comment by tvillani** [comment]
En el nuevo release, directamente no me incluye los mapas. Están los botones para llamar a las sucursales (ambos andan bien) y para enviar una consulta. pero no figuran los mapas. SI se complica mucho hacer ese linkeo, creo que lo podemos dejar como estaban antes. Eso del link era más una sugerencia que un reporte de bug.

**Comment by WEREMSOFT** [comment]
Ok, lo reviso de nuevo. No entiendo por qeu dejó de funcionar.

**Comment by tvillani** [comment]
Acabo de chequearlo nuevamente y figuran los mapas correctamente. No se si sacaste un release en el medio desde la última vez que lo revisé, pero anda correctamente. Clickando en ambos mapas sale bien la opción de ir a googlemaps, y de paso chequeé llamadas y tb todo OK.
