### ISSUE TITLE
DDN en la llamada a Urquiza

### ISSUE THREAD

**Issue by WEREMSOFT** [WEREMSOFT/nka20140804#14]
En la página de contacto, al intentar llamar a urquiza con el boton destinado para tal fin(el boton dice "llamar a sucursal cap fed", este no usa DDN(discado directo nacional), es decir, omite el 011, si uno esta desde una provincia, falla.

**Comment by WEREMSOFT** [comment]
Tomas, estoy probando esto y ahora agrega el prefijo 011 en ambas sucursales. Podes volver a chequear que este bug siga existiendo? Yo lo veo bien.

Un abrazo.

**Comment by tvillani** [comment]
Resuelto. Ambos botones para llamar a sucursales andan perfecto. Se puede cerrar.

**Comment by WEREMSOFT** [comment]
ciero
