### ISSUE TITLE
Criterios de orden en menúes finales.

### ISSUE THREAD

**Issue by WEREMSOFT** [WEREMSOFT/nka20140804#17]
OK. Pero algunos productos no son bien filtrados.

Pareciera como si algunos productos tuvieran el campo q se utiiliza como criterio vacío o en un formato incorrecto y el filtro lo lee como 0.(ej botas mont y botas trekk)

**Comment by WEREMSOFT** [comment]
No entiendo el bug. Estoy en la categoría "actividades de montaña"->"calzado - botas de montaña"->"botas de montaña"

y veo los siguientes precios

5111.15
7027.83
7766.73
8944.52
10365.6
11066.76

Ordenado de menor precio a mayor precio. Lo cual esta bien. Si cambio el orden a "ordenado por mayor precio" tengo lo siguiente: 

11066.76
10365.6
8944.52
7766.73
7027.83
5111.15

Los filtros parecen funcionar bien. Las botas de treking también funcionan bien.

No comprendo el bug. Por favor verificar que el mismo siga estando presente.

**Comment by tvillani** [comment]
Solucionado.
En la primera prueba hecha en Febrero, algunas categorías no se filtraban bien, entre ellas las dos de botas. En particula, seleccionando "ordenar por precio de menor a mayor", quedaban dos artículos de los más caros arriba, y después sí arrancaba la lista acorde al criterio. Parecía como si esos dos productos no tuvieran cargado el campo según el cual se ordena. lo cual era llamativo porque tenían el precio asignado correctamente.
De todos modos recién chequée un par de categorías, incluyendo esas dos, y todo funciona correctamente.
