### ISSUE TITLE
Al enviar pedido no pide forma de pago

### ISSUE THREAD

**Issue by WEREMSOFT** [WEREMSOFT/nka20140804#18]
En el formulario de datos de envío, el campo "forma de pago" debería ser obligatorio. No lo es.

**Comment by WEREMSOFT** [comment]
Tomas, podes chequear que este bug se haya solucionado? Si esta solucionado cerralo o asignamelo a mi. Es para llevar un tracking de lo que se va solucionando, teniendo una confirmación de tu parte de lo que yo entiendo que esta solucionado. Si no entendes algo dejá un comentario aca mismo. Gracias

**Comment by tvillani** [comment]
Este bug en particular nunca lo habia tenido en la version para android 2.2 que es la que tengo en mi cel. De todos modos lo chequeé y anda perfecto. Me salta el prompt de "Completar todos los campos con * ".
A decir verdad el campo de "Tipo de Pago" no tiene astersico, por lo que si quisiéramos ser finos habría que agregárselo para mayor claridad, pero aún así como esta hora, si se deja incompleto dicho campo, el prompt salta igual.

**Comment by WEREMSOFT** [comment]
Cierro bug, abro bug #23 para agregar el asterisco al campo "Tipo de pago"
