### ISSUE TITLE
Selección Correo Argentino a Sucursal

### ISSUE THREAD

**Issue by tvillani** [WEREMSOFT/nka20140804#19]
Este bug tiene varios puntos, todos relacionados al mismo tema, a saber:

1)Cuando se selecciona a sucursal, los nuevos campos que se abren ("DNI", "Sucursal de CA", y posteriormente "Dirección" (de Sucursal)), se abren afuera del campo visual por defecto. No se si es un problema de mi cel, del android viejo, o general, pero te lo dejo por las dudas.

2) Si cambio la provincia de envío no se me actualiza el listado de sucursales disponibles en esa provincia, sino que se mantiene el listado de las sucursales correspondientes a la provincia seleccionada anteriormente (vacío si no había pcia seleccionada en un principio).
De todos modos este 2do punto no es tan relevante para los compradores loggeados porque en general la provincia que está cargada es la correcta. Es más problemático en el caso de quienes compran como invitados porque como en principio la provincia no está cargada el listado de sucursales disponibles está vacío y no se actualiza al seleccionar la provincia.
Me permito sugerir que al corregir esto, a su vez, habría que cambiar el orden de los campos, porque el campo de opcion de sucursales de Correo Argentino figura antes (en orden secuencial de llenado) que el campo de Provincia, por lo que, incluso si se actualizaran las opciones del primero al seleccionar la opción del segundo, quedaría poco intuitivo para el usuario.

3) Un detalle adicional, que más que bug es una sugerencia relacionada con este punto.
 Al igual que como te comenté con el caso de la "Forma de pago": el campo de DNI de llenado obligatorio (si se deja vacío salta el prompt) pero le podríamos agregar el * (caracter de asterisco) para que quede más claro.

**Comment by WEREMSOFT** [comment]
Separo este bug en 3: #20, #22 y #22.

Es importante que los bugs esten separados para poder cerrarlos más prolijamente. Supongamos que soluciono el bug #22, que es un bug visual y se soluciona fácil, no puedo cerrar el bug hasta que solucione los otros 2, que son mas complicados.

**Comment by tvillani** [comment]
Ok. Buenísimo, La próx te los separo a todos y a lo sumo en el comentario te dejo la referencia al otro issue.

**Comment by WEREMSOFT** [comment]
gracias!
