### ISSUE TITLE
Cuando se selecciona a sucursal, los nuevos campos se abren afuera del campo visual.

### ISSUE THREAD

**Issue by WEREMSOFT** [WEREMSOFT/nka20140804#20]
Cuando se selecciona a sucursal, los nuevos campos que se abren ("DNI", "Sucursal de CA", y posteriormente "Dirección" (de Sucursal)), se abren afuera del campo visual por defecto. No se si es un problema de mi cel, del android viejo, o general, pero te lo dejo por las dudas.

**Comment by WEREMSOFT** [comment]
en celulares viejos no se tiene control sobre la posición precisa de la página, lamentablemente no hay mucho que se pueda hacer.

**Comment by tvillani** [comment]
OK. Si no se puede solucionar lo cerramos nomás. En todo caso cuando hagamos la prueba final con las 3 versiones, si llegara a aparecer algo de este estilo, lo reportamos acá.
Slds.
